# -*- coding: utf-8 -*-
"""titanic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1se0i0OjAqGfT_hjH7mFpPZQiL7H0NH90
"""

import pandas as pd
import csv

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

train

from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier()

train.isnull().sum()

train['Age'].fillna((train['Age'].mean()), inplace=True)

train['Embarked'].fillna((train['Embarked'].value_counts().index[0]), inplace=True)

train.drop('Cabin', axis = 1, inplace = True)

train.isnull().sum()

test['Age'].fillna((test['Age'].mean()), inplace=True)
 test['Embarked'].fillna((test['Embarked'].value_counts().index[0]), inplace=True)
 test['Fare'].fillna((test['Fare'].value_counts().index[0]), inplace=True)
 test.drop('Cabin', axis = 1, inplace = True)

test.isnull().sum()

sex = pd.get_dummies(train['Sex'], drop_first=True)
embarked = pd.get_dummies(train['Embarked'], drop_first=True)
train.drop(['Name', 'Sex', 'Ticket', 'Embarked'], axis = 1, inplace = True)
train = pd.concat([train, sex, embarked], axis=1)

train

sex = pd.get_dummies(test['Sex'], drop_first=True)
embarked = pd.get_dummies(test['Embarked'], drop_first=True)
test.drop(['Name', 'Sex', 'Ticket', 'Embarked'], axis = 1, inplace = True)
test = pd.concat([test, sex, embarked], axis=1)

test

X_train = train.drop(['PassengerId', 'Survived'], axis = 1)
y_train = train['Survived']
X_test = test.drop("PassengerId", axis=1).copy()

from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier()

random_forest.fit(X_train, y_train)
y_pred = random_forest.predict(X_test)

accuracy = round(random_forest.score(X_train, y_train) * 100, 2)
print('Accuracy: ', accuracy)

real_test = pd.DataFrame({
    "Survived": y_pred
})
gen = pd.read_csv('gender_submission.csv')
gen.drop('PassengerId', axis = 1, inplace = True)
from sklearn.metrics import accuracy_score
print(accuracy_score(gen, real_test)*100)

real_test

gen

Submission = pd.DataFrame({
    "PassengerId": test['PassengerId'],
    "Survived": y_pred
})

Submission.to_csv('Submission.csv', index = False)

Submission

